---
count: 8
default:
  restart: 0
  wait: 0
editor:
  files:
    eg:
      - some-file.eg
name: data-context-bem
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    watch:
      - lib
      - bin
      - tests
  2: []

  3: []

  4: []

  5: []

  6: []

  7: []

  8: []

